stages:
  drafts:
    prompt: agents/planner.md
    pool: planners
    model: opus
    max_budget_usd: 10
    permission_mode: plan
    disallowed_tools:              # in addition to defaults
      - Edit
      - Write
    transitions:
      PASS: plans
      SPLIT: plans
      FAIL: failed

  plans:
    prompt: agents/planner.md
    pool: planners
    model: opus
    max_budget_usd: 10
    permission_mode: plan
    disallowed_tools:
      - Edit
      - Write
    transitions:
      PASS: review
      SPLIT: review
      FAIL: failed

  review:
    prompt: agents/reviewer.md
    pool: reviewers
    model: opus
    permission_mode: plan
    disallowed_tools:
      - Edit
      - Write
      - NotebookEdit
    transitions:
      PASS: build
      REJECT: plans
      FAIL: failed

  build:
    prompt: agents/builder.md
    pool: builders
    model: sonnet
    max_budget_usd: 8
    # inherits default disallowed (no push, no rm -rf, no curl)
    # no additional restrictions — builder needs Edit, Write, Bash
    transitions:
      PASS: test
      FAIL: failed
    inner_loop:
      on_reject_from: test
      test_prompt: agents/tester.md
      max_iterations: 5

  test:
    prompt: agents/tester.md
    pool: testers
    model: sonnet
    disallowed_tools:
      - Edit
      - Write
      - NotebookEdit
    transitions:
      PASS: code-review
      REJECT: build
      FAIL: failed

  code-review:
    prompt: agents/code-reviewer.md
    pool: code-reviewers
    model: opus
    permission_mode: plan
    disallowed_tools:
      - Edit
      - Write
      - NotebookEdit
    transitions:
      PASS: draft-pr
      REJECT: build
      FAIL: failed

  draft-pr:
    prompt: agents/pr-creator.md
    pool: pr-creators
    allowed_tools:                 # explicitly allow push for this stage
      - Bash(git push *)
      - Bash(gh pr create *)
    disallowed_tools:
      - Edit
      - Write
      - NotebookEdit
    transitions:
      PASS: done
      FAIL: failed

max_attempts: 3
